# Generated by Django 6.0.7 on 2026-07-15 22:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=140)),
                ('title_ar', models.CharField(blank=True, max_length=140)),
                ('genre', models.CharField(blank=True, max_length=40)),
                ('summary_en', models.TextField(blank=True)),
                ('summary_ar', models.TextField(blank=True)),
                ('default_locale', models.CharField(default='en', max_length=2)),
                ('prompt', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('failed', 'Failed'), ('removed', 'Removed')], default='draft', max_length=10)),
                ('cover_url', models.CharField(blank=True, max_length=500)),
                ('service_game_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('save_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('remix_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
                ('remixed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remixes', to='games.game')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField()),
                ('change_summary', models.CharField(blank=True, max_length=280)),
                ('play_url', models.CharField(blank=True, max_length=500)),
                ('service_version_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='games.game')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='games.gameversion')),
            ],
            options={
                'ordering': ['game', 'version_no'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.gameversion'),
        ),
        migrations.CreateModel(
            name='GenerationJobRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_job_id', models.CharField(db_index=True, max_length=64)),
                ('type', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('remix', 'Remix')], default='create', max_length=8)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('awaiting_input', 'Awaiting input'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='queued', max_length=16)),
                ('stage', models.CharField(blank=True, max_length=32)),
                ('prompt', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='games.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gameversion',
            name='created_by_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='games.generationjobref'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'visibility', '-published_at'], name='games_game_status_5d10e9_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-created_at'], name='games_game_created_1d9304_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameversion',
            unique_together={('game', 'version_no')},
        ),
    ]
