# Generated by Django 6.0.7 on 2026-07-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjobref',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
