# Generated by Django 6.0.7 on 2026-07-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='external_price_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='subscription',
            name='external_subscription_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
